spring:
  #  config:
  #    import: classpath:/application-key.yml
  profiles:
    active: refactor
  application:
    name: refactor
  jackson:
    date-format: 'yyyy-MM-dd'
    time-zone: "Asia/Seoul"

cloud:
  aws:
    region:
      static: ap-northeast-2