spring:
  datasource:
    url: ${MYSQL_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-pool
      catalog: dev
      minimum-idle: 5
      maximum-pool-size: 100
      data-source-properties:
        idleTimeout: 600000
        maxLifetime: 1800000
        minimumIdle: 5
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-test-query: select 1
      auto-commit: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show-sql: true
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_USERNAME}
    password: ${NAVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
---

springdoc:
  use-fqn: true
  cache:
    disabled: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    tags-sorter: alpha
    operations-sorter: alpha
    groups-order: asc
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---

logging:
  level:
    org.hibernate:
      SQL: debug
      type: debug
    com.zaxxer.hikari.HikariDataSource: error

---

jwt:
  secret: ${JWT_SECRET_KEY}

---

hrd:
  api:
    key: ${API_KEY}
